### ISSUE TITLE
Homepage view breaks on EE2.8 with PHP 5.4+

### ISSUE THREAD

**Issue by caweidmann** [iainurquhart/publish_prefixes#2]
Homepage view breaks and it outputs a string that starts with "Array...". Any help on how to resolve would be appreciated.

**Comment by kmgdevelopment** [comment]
Seeing this too. [This hack](https://github.com/iainurquhart/publish_prefixes/pull/1) doesn't seem to work anymore.

**Comment by nate8684** [comment]
I'm dealing with this issue as well... Great little extension, just wish it didn't blow my homepage up

**Comment by jackmcpickle** [comment]
:+1: please

**Comment by jperasmus** [comment]
[This](https://github.com/iainurquhart/publish_prefixes/pull/1/files) core update/hack worked for me.
